<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ReceiptReimbursementAPI.Model\ReceiptReimbursementAPI.Model.csproj" />
    <ProjectReference Include="..\ReceiptReimbursementAPI.Data\ReceiptReimbursementAPI.Data.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
